name: Trigger Prefetch Feeds Job

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: "Deploy target"
        required: true
        default: staging
        type: choice
        options:
          - staging
          - prod
  schedule:
    - cron: "0 * * * *"

jobs:
  trigger-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env_name: staging
            project_id: ${{ vars.GCP_PROJECT_ID_STG }}
            region: ${{ vars.GCP_REGION_STG }}
            job_name: prefetch-feeds
            secret_name: GCP_RUN_JOB_KEY_STG
            trigger: push
          - env_name: prod
            project_id: ${{ vars.GCP_PROJECT_ID_PRD }}
            region: ${{ vars.GCP_REGION_PRD }}
            job_name: prefetch-feeds
            secret_name: GCP_RUN_JOB_KEY_PRD
            trigger: workflow_dispatch
    env:
      SHOULD_RUN: ${{ (github.event_name == 'push' && matrix.trigger == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.target_environment == matrix.env_name) || github.event_name == 'schedule' }}
    steps:
      - name: Skip if not target environment
        if: ${{ env.SHOULD_RUN != 'true' }}
        run: echo "Skipping execution for ${{ matrix.env_name }}"

      - name: Authenticate to Google Cloud
        if: ${{ env.SHOULD_RUN == 'true' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets[matrix.secret_name] }}

      - name: Execute Cloud Run Job
        if: ${{ env.SHOULD_RUN == 'true' }}
        run: |
          gcloud config set project ${{ matrix.project_id }}
          gcloud run jobs execute ${{ matrix.job_name }}             --region=${{ matrix.region }}             --quiet

      - name: Summary
        if: ${{ env.SHOULD_RUN == 'true' }}
        run: |
          echo "Triggered job ${{ matrix.job_name }} in ${{ matrix.env_name }} (${{ matrix.project_id }})" >> $GITHUB_STEP_SUMMARY
